# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89212021fb14db37946f7c0b8a7ec5b30444f90dd40fc22aa52c2edd448b795a0940bbbefc90a8b111930fc04e902414f2ad81176db741ac02f62f4b58b7fed7

test:
  secret_key_base: 5618f8fc509922bd01d51931864e29bce02e963fa2ecb4ba161a1f54c8f59aa3a7deeebf24d621545b95a50212c6a944e6d5980a999ed78a129d0b6eb4ec7c0d


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
